### ISSUE TITLE
[Event][Call for Proposal]PyData Global would love to see proposals form PyLadies

### ISSUE THREAD

**Issue by Cheukting** [pyladies/info#13]
Check out PyData Global 2020 (November 11th-15th), the very first fully-online PyData! Go to global.pydata.org to learn more. Looking to give a talk in 2020? The CFP is now open (https://global.pydata.org/pages/cfp.html), closing on August 2nd!

*About the conference*
Title: PyData Global 2020 Online Conference 
Date and time: November 11th-15th
Hosts: PyData/NumFOCUS
Description:
PyData Global is the very first fully-online PyData conference. Join our global community for five days packed with talks, tutorials, posters, open-source sprints and a digital hallway track.
For more information, check out global.pydata.org
The CFP is now live! Tickets will be on sale soon at the website.

**Comment by Mariatta** [comment]
Thanks!
