### ISSUE TITLE
Requesting a a PyLadies Sponsorship for PyGotham TV (October 2-3, 2020)

### ISSUE THREAD

**Issue by jonafato** [pyladies/info#14]
***The Basics***

- Are you a PyLady or an [Ally](https://github.com/pyladies/info/blob/main/README.md#allyship-defined)? Ally

- What is the event about? PyGotham is New York City's annual Python conference. It's a general Python conference covering any topics relevant to the Python community including (but not limited to) web development, data science, community topics, and ethics. For an example of the types of content featured at PyGotham, please see [2019's schedule](https://2019.pygotham.org/talks/). 

- What language is your event in? English

- Where is your event Code of Conduct? Please provide the link. https://2020.pygotham.tv/about/code-of-conduct/

- How does the event tie into the PyLadies [goals and initiatives](https://pyladies.com/about/)? PyGotham's goals include the promotion of and education about Python in the New York City area. We strive to provide a welcome environment for New York's diverse developer community (as well as our guests travelling from out of town).

- How will support from the PyLadies enhance the event? NYC PyLadies has had a booth at PyGotham for the past two years. A portion of the attendees that was not aware of PyLadies learned about the organization at the conference and gotten involved. NYC PyLadies is one of PyGotham's strongest partnerships and runs call for proposals workshops that result in talks in the conference schedule each year. We'd like to use our online event's broader reach to introduce attendees to PyLadies on a more global scale.

- When and where is the event taking place? Online October 2-3, 2020

- Is there an official page or document for the event? Please provide a link. https://2020.pygotham.tv

- What are the benefits for the sponsorship (e.g. promotion, event tickets)? PyGotham TV 2020 community sponsorships are available at gold and silver tier equivalent benefits defined in the [sponsorship prospectus](https://2020.pygotham.tv/sponsors/prospectus/). Benefits include inclusion on the website's sponsors page, video ads during the event, and a virtual booth to facilitate one-on-one discussions with attendees. (Note: PyGotham sponsorships typically include tickets to the event. This year's event is free to attend for all.)

***The Funding or Support***

- What do you need from the PyLadies? (Check all that apply)

  - [x] Outreach 👪
  - [ ] Speakers 🗣
  - [ ] Volunteers 🏋️‍♀️
  - [x] Other 🤷‍♂️

- Based on the above please let us know the quantity and reason for the need. PyGotham is always looking for help spreading the word about the conference. If you choose to accept the gold-tier sponsorship, we ask that someone from the organization put together a video for ad breaks and commit to being present and interacting with attendees during the conference.

- Are you requesting funding or resources from other diversity and inclusion minded tech groups? Please provide relevant information. PyGotham TV is not requesting funding from diversity and inclusion groups in 2020. Additional community sponsorships are available, and we'll be announcing those partnerships as we confirm them. Introductions to other groups that fit with PyGotham's mission of promoting Python and education in the New York area are welcome.

***Final Thoughts***

- When do you need an answer by? If sponsorship invitation is accepted, ad videos are due by September 10th

- Any additional details you want to provide? 

- Are there any other PyLadies working with you on this? If so, please tag them here. @econchick 

**STEP 2**

_This section is for the PyLadies Sponsorship team.  It will help us track the conversation and the deets that come out of the decision._

- Reviewed at meeting date:
- Status: Approved/Rejected

**STEP 3**

_Once the event is over we would love to hear about how it went._

- Please provide a link to a post or provide a brief synopsis of how the event went.

- Got pics? Please provide a link where PyLadies can access them.

/cc @pyladies/pyladies-global-admin
/cc @pyladies-global-contributors

**Comment by lorenanicole** [comment]
Thanks for opening this @jonafato! We'll get started reviewing this, sorry for the lateness in reply!

**Comment by Mariatta** [comment]
Hi @jonafato, we've discussed this today, and we've approved the sponsorship request. At the moment I don't think we have the capacity to manage the gold sponsorship level, so please consider us for the silver sponsorship level. 

We can help share the event through our social media cc @pyladies/communications. Do you have a specific tweet copy for us? Any specific link we should share? And let us know what else do you need from us to help with the outreach. Thanks.

**Comment by lorenanicole** [comment]
I'd love to help with this too!

**Comment by jonafato** [comment]
Hi there! Sorry for the delay, it's been a busy time leading up to the conference. All we'll need in order to list PyLadies as a conference sponsor is a logo, link, and short blurb of text to post on our sponsors page. You can see last year's details at https://2019.pygotham.org/sponsors/#pyladies for reference.

We don't have specific tweet copy, but a retweet or quote tweet of [this tweet](https://twitter.com/PyGotham/status/1303002601563267072) would be great!

**Comment by lorenanicole** [comment]
Thanks! @pyladies/communications can you take care of this?

**Comment by Marie-L** [comment]
Sure, thanks @lorenanicole & @Mariatta ! 

Hi @jonafato, I'll RT this evening (but it will be a more recent [tweet](https://twitter.com/PyGotham/status/1311687255984144384?s=20). I hope that's ok. Please let me know if you need anything else. Thanks !

**Comment by jonafato** [comment]
Sounds great, thanks! Just need to know what information to post to our sponsors page. I've linked the 2019 page for reference, and we can reuse that if it's easiest.

**Comment by Marie-L** [comment]
@jonafato you're welcome! Yes, please reuse last year's info. Thanks !
