### ISSUE TITLE
We would like to learn more about how to sponsor PyLadies (in Seattle)

### ISSUE THREAD

**Issue by gherri** [pyladies/info#17]
Hello,
My name is Gunawan Herri, VP of Engineering at a mid-size company called Domain Tools, HQ in downtown Seattle. 

I'm reaching out to you to learn more about PyLadies (its program, sponsorship, etc.)  and the possibility of collaborating together by sponsoring PyLadies as part of our Diversity and Inclusion initiatives. 

One of my female developers is a member of your chapter in Texas and speaks highly of the organization.

My emails to both sponsors@pyladies.com and seattle-pyladies@pyladies.com bounced back.

Hope to hear and connect with you soon...

Regards,
Gunawan Herri
gherri@domaintools.com
VP of Engineering
Domain Tools LLC

**Comment by Mariatta** [comment]
Thanks @gherri I've shared this with Seattle organizers @pyladies/seattle
