### ISSUE TITLE
How to become a member of PyLadies?

### ISSUE THREAD

**Issue by zubiamansoor** [pyladies/info#18]
Hi,

My name is Zubia Mansoor. I'm a master's student of statistics at Simon Fraser University. I'd like to know how I can get more involved with Pyladies.

Regards, 
Zubia Mansoor
M.Sc. Statistics
Simon Fraser University 
8888 University Dr., Burnaby, B.C. V5A 1S6 
Email: zmansoor@sfu.ca

**Comment by Mariatta** [comment]
Thanks for your interest in PyLadies! We have a Vancouver chapter at https://www.meetup.com/PyLadies-Vancouver/ 
There is no formal membership to join the local group. You can just join any of the upcoming meetups. 
Please also join us in Slack under #city-vancouver.

If you're looking to be more involved with the global PyLadies, you can register as a member here https://members.pyladies.com/ and participate and vote in our upcoming election.
