### ISSUE TITLE
 Verification of Logo as per standard guidelines. 

### ISSUE THREAD

**Issue by jeewanjotkaur** [pyladies/info#24]
**PyLadies Mohali** chapter has created a logo so that we can use it on our social media accounts to spread the word about our chapter here in Mohali, India. We have used standard word trademark and also the standard geek along with the map of the state(PUNJAB), Please have a look if everything is as per standard guidelines.

![image](https://user-images.githubusercontent.com/32723154/97070481-2ad9ff80-15f6-11eb-975a-1d1d6b8b3143.png)

**Comment by Mariatta** [comment]
The logo looks good. Thank you. No concern from our side.
