### ISSUE TITLE
Partnering with Pyladies

### ISSUE THREAD

**Issue by KatieZhaoPDT** [pyladies/info#3]
Hello, 

Hope this note finds you healthy and well. PDT Partners is a quant fund based in Midtown Manhattan and we would like to partner with the Pyladies team as a corporate sponsor. One of our ideas is hosting our first virtual session on engineering opportunities in quant finance. The series will be called “Demystifying careers in quant finance”. We will have a panel of engineers from different backgrounds (including an intern who will be returning full time) who will be discussing their experience and transition of skills into quant finance. We would like to virtually host your members in this session. Please let me know the best person to contact on your team.

Thanks,
Katie

**Comment by Mariatta** [comment]
Thanks for the message, Katie. I've shared this with our NYC chapter.

**Comment by KatieZhaoPDT** [comment]
Thank you so much Marietta. I received an a message to post on your meetup comments channel, I was wondering if it would be possible to  circulate the more amongst the Pyladies membership? We’re happy to have folks from different location join our webinar session.  I included details below on the event, please let me know if there is more information I can share?

Thanks much,
Katie



Webinar on June 17th, 2020 from 1pm - 2pm EST
Sign Up here: jst.me/pp52

Thinking about a career in tech, but never considered a path in quantitative finance?

During our 1-hour webinar, a panel of current PDT Partners technologists will talk about their career paths that led them to our firm, projects they’re currently working on, and commonly asked questions they've received from people outside the quantitative finance industry. We’ll also be giving a brief overview of the different groups within our technology organization.

A career in quant finance shouldn’t feel out of reach. Our engineers come from a wide variety of backgrounds, ranging from startups and big tech, to well-known financial institutions. We’re always looking for growth-minded individuals from any industry who love digging into data-driven problems.

We’ll have the chat open during the webinar for you to ask our panelists questions, but we kindly ask you to submit questions when you register about specific topics you’re curious about.

We look forward to seeing you virtually on June 17th. Please feel free to invite friends!
