### ISSUE TITLE
Subdomain takeover

### ISSUE THREAD

**Issue by JoeMilian** [pyladies/info#30]
Hey,

I noticed you had an unclaimed GitHub page, I took it over so no attacker is able to use it.

The subdomain: https://blog.pyladies.com/

Github suggests the following: "We strongly recommend not using wildcard DNS records, such as *.example.com. A wildcard DNS record will allow anyone to host a site at one of your subdomains."

I hope I have informed you enough, If there are any issues please don't hesitate to message me.

Kind regards,

Joe (https://twitter.com/JoeMilian1)

**Comment by Mariatta** [comment]
Thanks for letting us know about this issue. I think this is fixed now.
