### ISSUE TITLE
FlaskCon call for papers

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyladies/info#4]
Greetings,

The [flaskcon](https://flaskcon.com/) CFP closes today. But as per the submissions, we'd like to extend the deadline by 7 days for pyladies and similar initiatives. We don't know how we can get the word out to the pyladies org. Thank You.

**Comment by Mariatta** [comment]
Thanks for sharing. I've posted this info in our PyLadies Slack channel.

**Comment by Abdur-rahmaanJ** [comment]
This tweet: https://twitter.com/FlaskCon/status/1269950178359865345?s=19 describes it

**Comment by Abdur-rahmaanJ** [comment]
Thanks for all !

**Comment by lorenanicole** [comment]
Thanks @Abdur-rahmaanJ !
