### ISSUE TITLE
Job posting question

### ISSUE THREAD

**Issue by emsaintm** [pyladies/info#40]
Hi, 

I filled out your job posting form about a month or so ago with a Software Engineer position for Mycroft AI.  I was wondering how many times that goes out?  It goes on your Slack jobs feed, right?  If you could let me know how all of that works, I would really appreciate it.  We are just trying to figure out everywhere that the job is posted currently, as well as anywhere that it was previously posted and expired. 

Thanks so much,
Emily St. Martin

**Comment by Mariatta** [comment]
Hi, if you fill in the form, then it just gets automatically posted to the `#feed-jobs` slack channel once, at the time the form was submitted. It does not get re-posted at a later time.

I saw that your job posting was indeed posted to our Slack channel on August 31st.

Hope this helps.

**Comment by emsaintm** [comment]
It helps a ton.  Thank you!
