### ISSUE TITLE
PyCon sponsorship

### ISSUE THREAD

**Issue by sheona-harry** [pyladies/info#46]
Got it. Thank you for your reply!

**Comment by Mariatta** [comment]
Hi @sheona-harry,

Thanks for reaching out. However the deadline for applying grant for attending PyCon US 2022 from has ended. You can view the timeline here: https://us.pycon.org/2022/attend/travel-grants/

There is no separate application to apply for PyCon Grant from PyLadies. You would go through the same application from the PyCon website, and in there there would be a checkbox to indicate that you would want to apply for PyLadies grant. The application usually closes 3 months ahead of the conference.

I would suggest subscribing to receive updates from PyCon so you can get notified about the grant application for next year's PyCon. Thank you.
