### ISSUE TITLE
Europython Lunch RSVP?

### ISSUE THREAD

**Issue by seiler-rivers** [pyladies/info#49]
Hello!

I am attending Europython this July in Dublin, and saw that Pyladies will be having a lunch the Friday of the conference. However, when I went to fill out the RSVP form on the website, it said I needed permission to access the Google form. 
Is there any way the form could be updated, or is there another way I can register my interest to attend?

Thanks!

**Comment by hypha** [comment]
Hello! There was a permission issue. Thanks a lot for reporting. Should be fixed now! And looking forward to seeing you in Dublin!

**Comment by Mariatta** [comment]
Thanks for looking into this @hypha!
