### ISSUE TITLE
Pyladies X IncubateIND | Community Partners

### ISSUE THREAD

**Issue by dexteroussingh** [pyladies/info#5]
Dear Team PyLadies,

I am writing this email to inform you about the latest IncubateIND initiative, AI.NXT. IncubateIND is on a mission to upskill 1 Million students and get them ready for the job. This initiative is supported by Microsoft and Nasscom FutureSkills.

It will be an exclusive opportunity for students to learn AI & Data Science technology under the guidance of technology experts from Microsoft. In addition to an enriching learning experience, each Participant will also receive an AI-900 Certification from Microsoft. Microsoft AI-900 Certification Course curriculum is designed to contribute towards the upskilling of students and making them proficient in Data Science Courses.

Website: https://incubateind.com/ainxt/

I would like you to come along with us as a Community Partner and help spread a word for the benefits of the community students & ask them to register for these courses. There are no commercials involved for anyone at any level.

Request you to have a look and let me know your feedback.

I will be happy to get over a call and explain the initiative to you in detail.

Looking forward to your feedback. 

Regards,
Shakti Singh
Community Head - IncubateIND
incubateind.com

**Comment by lorenanicole** [comment]
@dexteroussingh we've created a sponsorship template you can use if you can please open [here](https://github.com/pyladies/info/issues/new?labels=sponsorship&template=sponsorship_template.md&title=Requesting+a+a+PyLadies+Sponsorship+for+%3CInsert+Event+Name+and+Date%3E)
