### ISSUE TITLE
Broken links in Pyladies.com footer

### ISSUE THREAD

**Issue by loren-c** [pyladies/info#66]
Just an FYI, I noticed that a couple of the links to social media accounts in the pyladies.com footer are broken - both the [LinkedIn icon](https://www.linkedin.com/groups/3984711/) & the [YouTube icon](https://www.youtube.com/pyladies) lead to 404 errors 
![pyladies com footer](https://github.com/pyladies/info/assets/93948470/df4c16e5-43b1-4bd8-8da0-4916afc61fe2)

I think the YouTube link should be updated to : https://www.youtube.com/@PyLadiesGlobal

Right now the LinkedIn icon seems to be trying to direct to a group; you might want to link to the Pyladies Global LinkedIn account: https://www.linkedin.com/company/pyladies-global/

Cheers!
Loren

**Comment by Mariatta** [comment]
Thanks for the report! It'll be fixed here: https://github.com/pyladies/pyladies/pull/617
