### ISSUE TITLE
Clarification on chapter email address

### ISSUE THREAD

**Issue by ujahbridget** [pyladies/info#9]
Hello, my name is Bridget, I write to find out if I can create an email account for my chapter which began not long ago. We have a challenge of getting updates and I am not sure how to go about the email account thing. I am the chapter lead of Abuja Nigeria Pyladies chapter.

**Comment by lorenanicole** [comment]
@ujahbridget can you reach out on our Slack? We are at slackin.pyladies.com. Thanks!
